# 웹 파일들을 C++ 배열로 변환해 바이너리에 내장한다.
# 사용: cmake -DOUT=<출력.cc> -DBASE=<web 디렉터리> -DFILES="a.html;b.js" -P embed.cmake
set(body "")
set(table "")
set(i 0)
foreach(f IN LISTS FILES)
    file(READ "${BASE}/${f}" hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
    string(LENGTH "${hex}" hexlen)
    math(EXPR size "${hexlen} / 5")
    if(f MATCHES "\\.html$")
        set(mime "text/html; charset=utf-8")
    elseif(f MATCHES "\\.js$")
        set(mime "text/javascript; charset=utf-8")
    elseif(f MATCHES "\\.css$")
        set(mime "text/css; charset=utf-8")
    elseif(f MATCHES "\\.svg$")
        set(mime "image/svg+xml")
    elseif(f MATCHES "\\.png$")
        set(mime "image/png")
    elseif(f MATCHES "\\.ico$")
        set(mime "image/x-icon")
    elseif(f MATCHES "\\.webmanifest$")
        set(mime "application/manifest+json")
    elseif(f MATCHES "\\.json$")
        set(mime "application/json; charset=utf-8")
    elseif(f MATCHES "\\.sh$")
        set(mime "text/plain; charset=utf-8")
    else()
        set(mime "application/octet-stream")
    endif()
    string(APPEND body "static const unsigned char d${i}[] = {${hex}};\n")
    string(APPEND table "    {\"${f}\", \"${mime}\", d${i}, ${size}},\n")
    math(EXPR i "${i} + 1")
endforeach()
file(WRITE "${OUT}.tmp" "// 자동 생성 파일 — 수정하지 말 것 (cmake/embed.cmake)\n#include \"assets.h\"\n\nnamespace moat::assets {\nnamespace {\n${body}\nconst Asset kAssets[] = {\n${table}};\n} // namespace\n\nconst Asset* find(std::string_view name) {\n    for (const auto& a : kAssets)\n        if (name == a.name) return &a;\n    return nullptr;\n}\n\n} // namespace moat::assets\n")
# 내용이 같으면 덮어쓰지 않아 불필요한 재컴파일을 막는다
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
